### ISSUE TITLE
Composite actions inputs are all strings by the JSON schema definition

### ISSUE THREAD

**Issue by ModeSevenIndustrialSolutions** [lfreleng-actions/actions-template#36]
The inputs to composite actions are actually all strings, and the JSON schema validation tool currently in our linting setup flags this (correctly) as an error:

```
Validate GitHub Actions..................................................Failed
- hook id: check-github-actions
- exit code: 1

Schema validation errors were encountered.
  action.yaml::$.inputs.type: Additional properties are not allowed ('type' was unexpected)
  action.yaml::$.inputs.repository: Additional properties are not allowed ('type' was unexpected)
  action.yaml::$.inputs.path: Additional properties are not allowed ('type' was unexpected)
```
The linting setup in question is here:
```yaml
  - repo: https://github.com/python-jsonschema/check-jsonschema.git
    rev: 06e4cc849d03f3a59ca223a4046f4bb5bb2aba6d  # frozen: 0.33.0
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
      - id: check-jsonschema
        name: Check GitHub Workflows set timeout-minutes
        args:
          - --builtin-schema
          - github-workflows-require-timeout
        files: ^\.github/workflows/[^/]+$
        types:
          - yaml
      - id: check-readthedocs
```
Currently, an initial commit containing type definitions on inputs (e.g. string, boolean, integer) will need the line below commenting out if it is to pass:

`- id: check-github-actions`

This information is potentially useful, and the problem is currently benign. Do we want to remove all the type definitions and keep enforcing the linting check of the JSON schema, or should we just remove or comment out this check in the current .pre-commit-config.yaml?
